Bookphoria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from Bookphoria.views import register, get_previous_edit_data_json, edit_profilejson
from Bookphoria.views import login_user 
from Bookphoria.views import logout_user
from django.urls import path
from Bookphoria.models import Like
from Bookphoria import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('review_list/', views.review_list, name='review_list'),
    #path('add_review/<int:product_id>/', views.add_review, name='add_review'),
    path('likes/<int:product_id>/', Like, name='like_book'),
    path('create/', views.create_profile, name='create_profile'),
    path('view/', views.view_profile, name='view_profile'),  
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('edit_profile_data_json/',get_previous_edit_data_json, name="edit_data_json"),
    path('edit_profilejson/', edit_profilejson, name='edit_profilejson'),
    path('', include('Homepage.urls')),
    path('profile/', include('Dashboard.urls')),
    path('detail/', include('DetailBook.urls')), 
    path('review/', include('ReviewApp.urls')),
]

Dashboard/urls.py
from django.urls import path
from .views import get_profile, add_book, get_books_json, get_reviews_json
app_name = 'Dashboard'

urlpatterns = [
    path('', get_profile, name='get-profile'),
    path('add-book/', add_book, name='add_book'),
    path('get-books/', get_books_json, name='get-books'),
    path('get-reviews/', get_reviews_json, name='get-reviews'),
]

Homepage/urls.py
from django.urls import path
from .views import home, get_books_json, like_book_more_efficient,all_books_page,like_book, get_categories, search_category_page,search_page, search_books_json,search_books_json_category,advanced_search
app_name = 'Homepage'

urlpatterns = [
    path('', home, name='home'),
    path('get-books/', get_books_json, name='get-books' ),
    path('all-books/', all_books_page, name='all-books-page'),
    path('search-books/<str:category>/', search_category_page, name='search-category-page'),
    path('search-books/<str:category>/<str:search_text>/', search_page, name='search-page'),
    path('search-books-json/<str:category>/<str:search_text>', search_books_json, name='search-books-json' ),
    path('search-books-json/<str:category>/', search_books_json_category, name='search-book-json-category'),
    path('get-categories/', get_categories, name='get-categories'),
    path('advanced-search-json/', advanced_search, name='advanced-search'),
    path('like-book-json/', like_book, name='like-book-json' ),
    path('like-book-more-efficient/',like_book_more_efficient,name='like_book_more_efficient')
]

Homepage/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class ImageUrl (models.Model):
    url = models.TextField()
    def __str__(self):
        return self.url

class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Book(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    title = models.CharField(max_length=255, blank=False, null=False)
    subtitle = models.CharField(max_length=255, blank=True, null=True )
    description = models.TextField(blank=True, null=True)
    authors = models.ManyToManyField('Author', related_name='authors_book')  
    publisher = models.CharField(max_length=100, blank=True, null=True)
    published_date = models.DateField(blank=True, null=True)
    language = models.CharField(max_length=10)
    currencyCode = models.CharField(max_length=10, blank=True, null=True)
    is_ebook = models.BooleanField()
    pdf_available = models.BooleanField()
    pdf_link = models.URLField(blank=True, null=True)
    thumbnail = models.URLField(blank=True, null=True)
    images = models.ManyToManyField(ImageUrl)
    categories = models.ManyToManyField('Category',  related_name='book_categories')
    price = models.CharField(max_length=255, blank=True, null=True)
    saleability = models.BooleanField(default=False)
    buy_link = models.URLField(blank=True, null=True)
    epub_available = models.BooleanField(default=False)
    epub_link = models.URLField(blank=True, null=True)
    maturity_rating = models.CharField(max_length=25)
    page_count = models.IntegerField(default=1,
        validators=[MinValueValidator(1)]
    )
    user_publish_time = models.DateTimeField(blank=True, null=True, default= timezone.now)
    user_last_edit_time = models.DateTimeField(blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='likes_book')

    def __str__(self):
        return self.title

Homepage/views.py
import json
from django.shortcuts import render
from django.http import JsonResponse
from .models import Book, Category
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from Bookphoria.models import UserProfile
from django.contrib.auth.models import User
from django.db.models import Count

# Create your views here.
@csrf_exempt
def advanced_search(request):
    search_parameters = json.loads(request.body)
    print(search_parameters)
    query = Q()
    if search_parameters['allWords']:
        words = search_parameters['allWords'].split()
        for word in words:
            query |= Q(title__icontains=word)
    
    if search_parameters['exactPhrase']:
        query &= Q(title__icontains=search_parameters['exactPhrase'])

    if search_parameters['atLeastWords']:
        words = search_parameters['atLeastWords'].split()
        at_least_query = Q()  # Query Q untuk at least words
        for word in words:
            at_least_query |= Q(title__icontains=word)
        query &= at_least_query

    if search_parameters['withoutWords']:
        words = search_parameters['withoutWords'].split()
        without_query = Q()  # Query Q untuk without words
        for word in words:
            without_query &= ~Q(title__icontains=word)
        query &= without_query

    books = Book.objects.prefetch_related('authors', 'images', 'categories', 'likes').select_related('user__auth_user').filter(query)
    book_list = []
    
    for book in books:
        book_data  = {
            'likes':  [{'username': user.username, 'userId': user.pk} for user in book.likes.all()],
            'fullname':book.user.auth_user.fullname,
            'username':book.user.auth_user.username,
            'id': book.pk,
            'title': book.title,
            'subtitle': book.subtitle,
            'description': book.description,
            'authors': [author.name for author in book.authors.all()],
            'publisher': book.publisher,
            'published_date': book.published_date.strftime('%Y-%m-%d') if book.published_date else None,
            'language': book.language,
            'currencyCode': book.currencyCode,
            'is_ebook': book.is_ebook,
            'pdf_available': book.pdf_available,
            'pdf_link': book.pdf_link,
            'thumbnail': book.thumbnail,
            'categories': [category.name for category in book.categories.all()],
            'images':[imageUrl.url for imageUrl in book.images.all()],
            'price': book.price,
            'saleability': book.saleability,
            'buy_link': book.buy_link,
            'epub_available': book.epub_available,
            'epub_link': book.epub_link,
            'maturity_rating': book.maturity_rating,
            'page_count': book.page_count,
            'user_publish_time': book.user_publish_time,
        }
        book_list.append(book_data)
    return JsonResponse({'books': book_list})

def home(request):
    #print(request.user.is_authenticated)
    user = request.user if request.user.is_authenticated else None
    profile = None
    if user:
        profile = UserProfile.objects.get(user=user)
    context = {
        'user': {
            'id': user.id if user else None,
            'username': user.username if user else None,
            'is_authenticated': True if user else False,
            'profile': profile
        }
    }
    return render(request, "home.html", context)

def all_books_page(request):
    user = request.user if request.user.is_authenticated else None
    profile = None
    if user:
        profile = UserProfile.objects.get(user=user)
    context = {
        'user': {
            'id': user.id if user else None,
            'username': user.username if user else None,
            'is_authenticated': True if user else False,
            'profile': profile
        }
    }
    return render(request, "allbooks-page.html", context)

@csrf_exempt
def get_categories(request):
    categories = Category.objects.all()
    categories_list = []
    for category in categories:
        categories_list.append(category.name)
    return JsonResponse({'categories':categories_list})
def search_page(request, category, search_text ):
    user = request.user if request.user.is_authenticated else None
    profile = None
    if user:
        profile = UserProfile.objects.get(user=user)
    context = {
        'user': {
            'id': user.id if user else None,
            'username': user.username if user else None,
            'is_authenticated': True if user else False,
            'profile': profile
        }
    }
    information = {
        'category':category,
        'search_text':search_text,
        'is_category_only':"False"
    }
    return render(request,'search-page.html', information)
def search_category_page(request,category):
    information = {
        'category':category,
        'search_text':'',
        'is_category_only':"True",
        'user': {
            'id': user.id if user else None,
            'username': user.username if user else None,
            'is_authenticated': True if user else False,
            'profile': profile
        }
    }
    return render(request, 'search-page.html', information)

@csrf_exempt
def search_books_json(request, category, search_text):
    books = []
    if(category == 'All'):
        books   = Book.objects.prefetch_related('authors', 'images', 'categories', 'likes').select_related('user__auth_user').filter(
        title__icontains=search_text.strip())
    else:
        books  = Book.objects.prefetch_related('authors', 'images', 'categories', 'likes').select_related('user__auth_user').filter(
        title__icontains=search_text, categories__name=category)
    book_list = []
    for book in books:
        book_data  = {
            'likes':  [{'username': user.username, 'userId': user.pk} for user in book.likes.all()],
            'fullname':book.user.auth_user.fullname,
            'username':book.user.auth_user.username,
            'id': book.pk,
            'title': book.title,
            'subtitle': book.subtitle,
            'description': book.description,
            'authors': [author.name for author in book.authors.all()],
            'publisher': book.publisher,
            'published_date': book.published_date.strftime('%Y-%m-%d') if book.published_date else None,
            'language': book.language,
            'currencyCode': book.currencyCode,
            'is_ebook': book.is_ebook,
            'pdf_available': book.pdf_available,
            'pdf_link': book.pdf_link,
            'thumbnail': book.thumbnail,
            'categories': [category.name for category in book.categories.all()],
            'images':[imageUrl.url for imageUrl in book.images.all()],
            'price': book.price,
            'saleability': book.saleability,
            'buy_link': book.buy_link,
            'epub_available': book.epub_available,
            'epub_link': book.epub_link,
            'maturity_rating': book.maturity_rating,
            'page_count': book.page_count,
            'user_publish_time': book.user_publish_time,
        }
        book_list.append(book_data)

    return JsonResponse({'books': book_list})

def search_books_json_category(request, category):
    books = []
    if(category == 'All'):
        books = Book.objects.prefetch_related('authors', 'images', 'categories', 'likes').select_related('user__auth_user').all()
    else:
        books = Book.objects.prefetch_related('authors', 'images', 'categories', 'likes').select_related('user__auth_user').filter(categories__name=category)
    book_list = []
    for book in books:
        book_data  = {
            'likes':  [{'username': user.username, 'userId': user.pk} for user in book.likes.all()],
            'fullname':book.user.auth_user.fullname,
            'username':book.user.auth_user.username,
            'id': book.pk,
            'title': book.title,
            'subtitle': book.subtitle,
            'description': book.description,
            'authors': [author.name for author in book.authors.all()],
            'publisher': book.publisher,
            'published_date': book.published_date.strftime('%Y-%m-%d') if book.published_date else None,
            'language': book.language,
            'currencyCode': book.currencyCode,
            'is_ebook': book.is_ebook,
            'pdf_available': book.pdf_available,
            'pdf_link': book.pdf_link,
            'thumbnail': book.thumbnail,
            'categories': [category.name for category in book.categories.all()],
            'images':[imageUrl.url for imageUrl in book.images.all()],
            'price': book.price,
            'saleability': book.saleability,
            'buy_link': book.buy_link,
            'epub_available': book.epub_available,
            'epub_link': book.epub_link,
            'maturity_rating': book.maturity_rating,
            'page_count': book.page_count,
            'user_publish_time': book.user_publish_time,
        }
        book_list.append(book_data)

    return JsonResponse({'books': book_list})

@csrf_exempt
def get_books_json(request):
    #books = Book.objects.prefetch_related('authors', 'images', 'categories', 'likes').select_related('user__auth_user').all()
    #books = Book.objects.prefetch_related('authors', 'images', 'categories', 'likes').select_related('user__auth_user').annotate(review_count=Count('reviews'))
    #reviews = Review.objects.all().select_related('user').values('rating')
    books = Book.objects.prefetch_related('authors', 'images', 'categories', 'likes').select_related('user__auth_user').annotate(review_count=Count('review'))
    book_list = []
    for book in books:
        book_data  = {
            'review_count': book.review_count,
            'likes':  [{'username': user.username, 'userId': user.pk} for user in book.likes.all()],
            'fullname':book.user.auth_user.fullname,

Homepage/templates/partials/all-books-navbar.html
<div id="navbar" class="fixed z-20 top-0  left-0 flex flex-col items-center w-full max-w-[100vw] ">
    <div class="w-full relative z-40 bg-violet-950 px-4 md:px-8 flex text-xl items-center  py-3 ">
        <h1 class="mr-4 text-white">BOOKPHORIA.</h1>

        <div class="hidden md:flex min-w-[50vw] max-w-[50vw] lg:min-w-[60vw] lg:max-w-[50vw]">
            <div class="flex grow">
                <label for="books-dropdown" class="mb-2 text-sm font-medium text-gray-900 sr-only">Books</label>
                <div class="relative flex items-center justify-center">
                    <button  data-dropdown-toggle="dropdown" class="dropdown-button-xl flex-shrink-0 z-10 inline-flex items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-gray-300 rounded-l-lg hover:bg-gray-200 " type="button">
                        <span  class="books-dropdown-current-value">All</span> <svg  class="books-dropdown-svg w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                    </svg>
                    </button>
                    <div  class="books-dropdown-content hidden absolute top-12 right-0 z-20 ">
                        <ul  class="books-dropdown-values flex flex-col py-2 text-sm text-gray-700  rounded-lg shadow w-44 overflow-y-auto bg-violet-950 dark:text-gray-200 h-[24rem]">
                          <li>
                            <button  class="block w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-value="Terbaru">Terbaru</button>
                          </li>
                          <li>
                            <button  class="block w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-value="Terlama">Terlama</button>
                          </li>
                          <li>
                            <button class="block w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-value="Paling Banyak Disukai">Paling Banyak Disukai</button>
                          </li>
                          <li>
                            <button class="block w-full  px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-value="Review Terbanyak">Review Terbanyak</button>
                          </li>
                        </ul>
                    </div>
                </div>                
                <div class="relative grow">
                    <input type="search" id="pc-search-input" class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-r-xl border-l-gray-50 border-l-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500" placeholder="Search Books..." required>
                    <button id="pc-search-answer" class="absolute top-0 right-0 p-2.5 text-sm font-medium h-full text-white bg-indigo-600 rounded-r-lg border-2 border-indigo-600  hover:bg-indigo-800 ">
                        <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                        </svg>
                        <span class="sr-only">Search</span>
                    </button>
                </div>
            </div>
        </div>

        <div class="ml-auto hidden md:flex pl-4 text-white text-xl lg:text-lg grow max-w-[25%] lg:max-w-[20%]  justify-between items-center ">
            <a  href="/"><i class="fas fa-home lg:text-2xl"></i></a>
            <a href="/all-books"><i class="fas fa-book  lg:text-2xl"></i></a>
            <a href="{% url 'Dashboard:get-profile' %}"><i class="fas fa-chart-bar  lg:text-2xl"></i></a>
            <a href="{% url 'view_profile' %}"><i class="fas fa-user  lg:text-2xl"></i></a>
          </div>
        <div  id="mobile-search-button"  class="ml-auto md:hidden text-white flex items-center ">
            <svg class="md:hidden w-4 h-4" onclick="toggleMobileNavbarBooks();" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
            <div onclick="openSidebarBooks()" class="md:hidden ml-6 fas fa-bars  text-white">
            </div>
        </div>
        
    </div>
    <div id="mobile-search-bar-books-mode" data-value="all-books-mode" class=" absolute top-12 left-0 flex items-center justify-center w-full py-3 px-4 bg-violet-950  transform -translate-y-96 transition-transform duration-300 ease-in-out">
        <div class="mx-auto flex w-[90vw] max-w-[90vw]">
            <div class="flex items-center   w-full">
                <div class="relative  flex items-center justify-center">
                    <button  data-dropdown-toggle="dropdown" class="dropdown-button-xl flex-shrink-0 z-10 flex justify-between items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-gray-300 rounded-l-lg hover:bg-gray-200 " type="button">
                        <p  class="truncate max-w-[5rem] books-dropdown-current-value">All</p> <svg  class="books-dropdown-svg w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                    </svg>
                    </button>
                    <div  class="books-dropdown-content hidden absolute top-12 left-0 z-20 ">
                        <ul  class="books-dropdown-values flex flex-col py-2 text-sm text-gray-700  rounded-lg shadow w-44 overflow-y-auto bg-violet-950 dark:text-gray-200 h-[24rem]">
                          <li>
                            <button  class="block w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-value="Terbaru">Terbaru</button>
                          </li>
                          <li>
                            <button  class="block w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-value="Terlama">Terlama</button>
                          </li>
                          <li>
                            <button class="block w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-value="Paling Banyak Disukai">Paling Banyak Disukai</button>
                          </li>
                          <li>
                            <button class="block w-full  px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-value="Review Terbanyak">Review Terbanyak</button>
                          </li>
                        </ul>
                    </div>
                </div>                
                <div class="relative grow  ">
                    <input type="search" id="mobile-search-input"  class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-r-xl border-l-gray-50 border-l-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500" placeholder="Search Books..." required>
                    <button id="mobile-search-answer" class="absolute top-0 right-0 p-2.5 text-sm font-medium h-full text-white bg-indigo-600 rounded-r-lg border-2 border-indigo-600  hover:bg-indigo-800 ">
                        <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                        </svg>
                        <span class="sr-only">Search</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
<script>

var isMobileNavbarBooksOpen = false;
var isSidebarBooksOpen = false;

window.addEventListener('resize', ()=>{
    const mobileSearchButton = document.getElementById("mobile-search-button");
    const mobileSearchBar = document.getElementById("mobile-search-bar-books-mode");
    if(!mobileSearchButton || !mobileSearchBar){
        return;
    }
    const screenWidth = window.innerWidth;
    let maxWidth = 768;
    if(screenWidth >= maxWidth){
        if(isMobileNavbarBooksOpen){
            closeMobileNavbarBooks()
        }
    }
})
window.addEventListener('resize', ()=>{
    const sidebar = document.getElementById('sidebar');
    if(!sidebar){
        return;
    }
    const screenWidth = window.innerWidth;
    if(screenWidth >= 768){
        if(isSidebarBooksOpen){
            closeSidebarBooks()
        }
    }
})


const openSidebarBooks = ()=> {
    const sidebar = document.getElementById('sidebar');
    sidebar.classList.remove('-translate-x-[100%]');
    sidebar.classList.add('translate-x-0');
    isSidebarBooksOpen = true;
}
const closeSidebarBooks = ()=> {
    const sidebar = document.getElementById('sidebar');
    sidebar.classList.remove('translate-x-0');
    sidebar.classList.add('-translate-x-[100%]');  
    isSidebarBooksOpen = false
}
const toggleMobileNavbarBooks = () => {
    if(isMobileNavbarBooksOpen){
        closeMobileNavbarBooks()
    }
    else{
        openMobileNavbarBooks()
    }
}
const closeMobileNavbarBooks = () => {
    const mobileSearchButton = document.getElementById("mobile-search-button");
    const mobileSearchBar = document.getElementById("mobile-search-bar-books-mode");
    mobileSearchButton.innerHTML = `<svg class="w-4 h-4" onclick="toggleMobileNavbarBooks();" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
</svg>
<div onclick="openSidebarBooks();" class="md:hidden ml-6 fas fa-bars  text-white">
</div>`;
    mobileSearchBar.classList.remove('translate-y-0');
    mobileSearchBar.classList.add('-translate-y-48');
    isMobileNavbarBooksOpen = false;    
}
const openMobileNavbarBooks = () =>{
    const mobileSearchButton = document.getElementById("mobile-search-button");
    const mobileSearchBar = document.getElementById("mobile-search-bar-books-mode");
    mobileSearchButton.innerHTML = `<div onclick="toggleMobileNavbarBooks();" class="fas fa-times w-4 h-4 text-red-500"></div>`;
    mobileSearchBar.classList.remove('-translate-y-48');
    mobileSearchBar.classList.add('translate-y-0');
    isMobileNavbarBooksOpen = true;
}
</script>

Homepage/templates/partials/dropdown.html
<div class="relative flex ">
    <div class="flex flex-col items-end ">
        <div id="dropdownDelayButton"  class="text-white bg-violet-950 hover:bg-indigo-950   font-medium rounded-lg text-xs px-5 py-2.5 text-center inline-flex items-center"><span id="dropdownButtonText">Dropdown Current Text</span><svg id="homeDropdownIcon" class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
          </svg>
        </div>
        <div id="dropdownDelay" class="hidden absolute top-12 right-0 z-20  bg-violet-950 divide-y divide-gray-100 rounded-lg shadow w-44 ">
            <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDelayButton">
              <li>
                <button  class="block w-full px-4 py-2 hover:bg-indigo-800" data-value="Terbaru">Terbaru</button>
              </li>
              <li>
                <button  class="block w-full px-4 py-2 hover:bg-indigo-800 " data-value="Terlama">Terlama</button>
              </li>
              <li>
                <button class="block w-full px-4 py-2 hover:bg-indigo-800 " data-value="Paling Banyak Disukai">Paling Banyak Disukai</button>
              </li>
              <li>
                <button class="block w-full  px-4 py-2 hover:bg-indigo-800 " data-value="Review Terbanyak">Review Terbanyak</button>
              </li>
            </ul>
        </div>
    </div>
</div>


<!-- Dropdown menu -->