Bookphoria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from Bookphoria.views import register, get_previous_edit_data_json, edit_profilejson
from Bookphoria.views import login_user 
from Bookphoria.views import logout_user
from django.urls import path
from Bookphoria.models import Like
from Bookphoria import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('review_list/', views.review_list, name='review_list'),
    #path('add_review/<int:product_id>/', views.add_review, name='add_review'),
    path('likes/<int:product_id>/', Like, name='like_book'),
    path('create/', views.create_profile, name='create_profile'),
    path('view/', views.view_profile, name='view_profile'),  
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('edit_profile_data_json/',get_previous_edit_data_json, name="edit_data_json"),
    path('edit_profilejson/', edit_profilejson, name='edit_profilejson'),
    path('', include('Homepage.urls')),
    path('profile/', include('Dashboard.urls')),
    path('detail/', include('DetailBook.urls')), 
    path('review/', include('ReviewApp.urls')),
]

Dashboard/urls.py
from django.urls import path
from .views import get_profile, add_book, get_books_json, get_reviews_json
app_name = 'Dashboard'

urlpatterns = [
    path('', get_profile, name='get-profile'),
    path('add-book/', add_book, name='add_book'),
    path('get-books/', get_books_json, name='get-books'),
    path('get-reviews/', get_reviews_json, name='get-reviews'),
]

Homepage/urls.py
from django.urls import path
from .views import home, get_books_json, like_book_more_efficient,all_books_page,like_book, get_categories, search_category_page,search_page, search_books_json,search_books_json_category,advanced_search
app_name = 'Homepage'

urlpatterns = [
    path('', home, name='home'),
    path('get-books/', get_books_json, name='get-books' ),
    path('all-books/', all_books_page, name='all-books-page'),
    path('search-books/<str:category>/', search_category_page, name='search-category-page'),
    path('search-books/<str:category>/<str:search_text>/', search_page, name='search-page'),
    path('search-books-json/<str:category>/<str:search_text>', search_books_json, name='search-books-json' ),
    path('search-books-json/<str:category>/', search_books_json_category, name='search-book-json-category'),
    path('get-categories/', get_categories, name='get-categories'),
    path('advanced-search-json/', advanced_search, name='advanced-search'),
    path('like-book-json/', like_book, name='like-book-json' ),
    path('like-book-more-efficient/',like_book_more_efficient,name='like_book_more_efficient')
]

Dashboard/forms.py
from django.forms import ModelForm
from Homepage.models import Book

class BookForm(ModelForm):
  class Meta:
    model = Book
    fields = ['thumbnail', 'authors', 'title', 'categories', 'publisher', 'language', 'page_count', 'published_date', 'currencyCode', 'price', 'description', 'is_ebook', 'pdf_available']

Dashboard/views.py
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from Bookphoria.models import UserProfile
from Dashboard.forms import BookForm
from Homepage.models import Book, Author, Category
#from Bookphoria.models import Review
from ReviewApp.models import Review

@login_required(login_url='/login/')
def get_profile(request):
    form = BookForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        add_book(request)
        return HttpResponseRedirect(reverse('Dashboard:get-profile'))
    books = Book.objects.prefetch_related('authors', 'images', 'categories').all()
    book_list = []
    user = UserProfile.objects.get(user=request.user)
    for book in books:
        book_data  = {
            'title': book.title,
            'subtitle': book.subtitle,
            'description': book.description,
            'authors': [author.name for author in book.authors.all()],
            'publisher': book.publisher,
            'published_date': book.published_date.strftime('%Y-%m-%d') if book.published_date else None,
            'language': book.language,
            'currencyCode': book.currencyCode,
            'is_ebook': book.is_ebook,
            'pdf_available': book.pdf_available,
            'pdf_link': book.pdf_link,
            'thumbnail': book.thumbnail,
            'categories': [category.name for category in book.categories.all()],
            'images':[imageUrl.url for imageUrl in book.images.all()],
            'price': book.price,
            'saleability': book.saleability,
            'buy_link': book.buy_link,
            'epub_available': book.epub_available,
            'epub_link': book.epub_link,
            'maturity_rating': book.maturity_rating,
            'page_count': book.page_count,
            'user_publish_time': book.user_publish_time
        }
        book_list.append(book.thumbnail)
        # print(book.thumbnail)
        # print(book_list)
    if user.profile_picture is None:
        user.profile_picture = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ03Q9ChkabFQ9M3syb-NEQOk9x34zv4pfFQ&usqp=CAU'
    context = {
        'books':book_list,
        'form': form,
        'user': user
    }
    return render(request, 'profile.html', context)

def visit_profile(request, username):
    form = BookForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        add_book(request)
        return HttpResponseRedirect(reverse('Dashboard:get-profile'))
    try:
        user = UserProfile.objects.get(username=username)
    except UserProfile.DoesNotExist:
        return render(request, 'user-not-exist.html')
    books = Book.objects.prefetch_related('authors', 'images', 'categories').all()
    book_list = []
    user = UserProfile.objects.get(username=username)
    print("=====================================")
    print(user)
    print("=====================================")
    for book in books:
        book_data  = {
            'title': book.title,
            'subtitle': book.subtitle,
            'description': book.description,
            'authors': [author.name for author in book.authors.all()],
            'publisher': book.publisher,
            'published_date': book.published_date.strftime('%Y-%m-%d') if book.published_date else None,
            'language': book.language,
            'currencyCode': book.currencyCode,
            'is_ebook': book.is_ebook,
            'pdf_available': book.pdf_available,
            'pdf_link': book.pdf_link,
            'thumbnail': book.thumbnail,
            'categories': [category.name for category in book.categories.all()],
            'images':[imageUrl.url for imageUrl in book.images.all()],
            'price': book.price,
            'saleability': book.saleability,
            'buy_link': book.buy_link,
            'epub_available': book.epub_available,
            'epub_link': book.epub_link,
            'maturity_rating': book.maturity_rating,
            'page_count': book.page_count,
            'user_publish_time': book.user_publish_time
        }
        book_list.append(book.thumbnail)
        # print(book.thumbnail)
        # print(book_list)
    if user.profile_picture is None:
        user.profile_picture = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ03Q9ChkabFQ9M3syb-NEQOk9x34zv4pfFQ&usqp=CAU'
    context = {
        'books':book_list,
        'form': form,
        'user': user
    }
    return render(request, 'visit-profile.html', context)

@csrf_exempt
def add_book(request):
    form = BookForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        new_book = form.save(commit=False)
        new_book.user = request.user

        new_book.save()

        print(Book.objects.filter(user=new_book.user).prefetch_related('authors', 'images', 'categories'))  
        return HttpResponse(b"CREATED", status=201)

    context = {'form': form}
    print("=======================NICE COKC=====================")
    return render(request, 'add_book.html', context)

@csrf_exempt
def get_books_json(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseForbidden()
    print(user)
    books = Book.objects.filter(user=user).prefetch_related('authors', 'images', 'categories')
    book_list = []
    for book in books:
        book_data  = {
            'title': book.title,
            'subtitle': book.subtitle,
            'description': book.description,
            'authors': [author.name for author in book.authors.all()],
            'publisher': book.publisher,
            'published_date': book.published_date.strftime('%Y-%m-%d') if book.published_date else None,
            'language': book.language,
            'currencyCode': book.currencyCode,
            'is_ebook': book.is_ebook,
            'pdf_available': book.pdf_available,
            'pdf_link': book.pdf_link,
            'thumbnail': book.thumbnail,
            'categories': [category.name for category in book.categories.all()],
            'images':[imageUrl.url for imageUrl in book.images.all()],
            'price': book.price,
            'saleability': book.saleability,
            'buy_link': book.buy_link,
            'epub_available': book.epub_available,
            'epub_link': book.epub_link,
            'maturity_rating': book.maturity_rating,
            'page_count': book.page_count,
            'user_publish_time': book.user_publish_time,
        }
        book_list.append(book_data)
    return JsonResponse({'books': book_list})

@csrf_exempt
def get_reviews_json(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseForbidden()
    print(user)
    reviews = Review.objects.filter(user=user)
    review_list = []
    for review in reviews:
        review_data  = {
           # 'thumbnail': review.thumbnail,
            'thumbnail' : review.photo.url if review.photo else "https://m.media-amazon.com/images/I/71lgQcXtPMS._AC_UF894,1000_QL80_.jpg",
            'title': "Sebuah Judul" if review.book.title is None else review.book.title,  # Review dr Review App ga include title
            'rating': review.rating,
            'content': review.content,
        }
        review_list.append(review_data)
    return JsonResponse({'reviews': review_list})

Dashboard/templates/user-not-exist.html
{% extends 'base-tailwind.html' %}
{% load static %}
{% block meta %}
    <title>Bookphoria</title>
{% endblock meta %}

{% block content %}
    
    {% include 'partials/navbar.html' %}
    {% include "partials/sidebar.html"  %}
    {% include "partials/loading-text.html"  %}\
        <section id="homeContent" class="hidden mt-16 md:mt-20 mx-12 flex md:flex-row md:flex-row flex-col flex-row gap-10">
            <div class="w-full flex flex-col items-center">
                <h2 class="text-xl mb-4 opacity-50">User does not exist</h2>
            </div>
        </section>
    <script>
async function refreshReviewList() {
    const reviewList = document.getElementById("review-list")
    const response = await fetch("/profile/get-reviews")
    const data = await response.json()
    reviewList.innerHTML = ""
    if (data.reviews.length == 0){
        reviewList.innerHTML = `<p>No reviews yet</p>`
    } else {
        data.reviews.forEach(review => {
            reviewList.innerHTML += "\n" +
            `<div class="border-2 rounded-xl p-2 shadow-lg flex gap-6 max-h-32">` +
                `<img src="${review.thumbnail}" class="h-full aspect-square object-cover shadow-xl rounded-xl"/>` +
                `<div>` +
                    `<h4 class="font-extrabold">${review.title}</h4>` +
                    `<i class="fa-solid fa-star"> ${review.rating}</i>` +
                    `<br class="mb-4"/>` +
                    `${review.content}` +
                `</div>` +
            `</div>`
        })
    }
}
  
async function refreshBookList() {
    const loading = document.getElementById('loading-text')
    try {
        loading.style.display = 'flex';
        await refreshReviewList()
        const bookList = document.getElementById("book-list")
        const response = await fetch("/profile/get-books")
        console.log("====================================")
        console.log(response)
        const data = await response.json()
        console.log(data)
        console.log("====================================")
        bookList.innerHTML = ""
        if (data.books.length == 0){
            bookList.innerHTML = `<p>No books yet</p>`
        } else {
            data.books.forEach(book => {
                bookList.innerHTML += "\n" +
                    `<img src="${book.thumbnail}" class="h-full w-auto object-contain shadow-xl"/>`
            })
        }
        loading.style.display = 'none';
    } catch (err) {
        console.log(err)
        loading.style.display = 'none';
    }
}
  
window.addEventListener("DOMContentLoaded", async ()=>{
    await refreshBookList()
    console.log("DOM Loaded")
    homeContent.classList.remove("hidden"); 
    function addBook() {
        fetch("{% url 'Dashboard:add_book' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#add-book-form'))
        }).then(refreshBookList)
  
        document.getElementById("add-book-form").reset()
        document.querySelector('[data-modal-hide="add-book-modal"]').click()
    }
  
    document.getElementById("submit_new_book").onclick = addBook
  
    function validateSize(input) {
        const fileSize = input.files[0].size / 1024 / 1024; // in MiB
        if (fileSize > 2) {
            alert('File size exceeds 2 MiB');
            input.value = '';
        }
    }
})
    </script>
    <script src="{% static 'js/profile.js' %}"></script>
    <script type="module" src="{% static 'js/firebase-upload.js' %}"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"/>
{% endblock content %}

Dashboard/templates/visit-profile.html
{% extends 'base-tailwind.html' %}
{% load static %}
{% block meta %}
    <title>Bookphoria</title>
{% endblock meta %}

{% block content %}
    
    {% include 'partials/navbar.html' %}
    {% include "partials/sidebar.html"  %}
    {% include "partials/loading-text.html"  %}\
        <section id="homeContent" class="hidden mt-16 md:mt-20 mx-12 flex md:flex-row md:flex-row flex-col flex-row gap-10">
            <div class="md:w-1/3 w-full flex flex-col items-center">
                <img
                    src="{{ user.profile_picture }}"
                    class="rounded-full mb-4"
                 />
                <h2 class="text-xl font-bold">{{ user.username }}</h2>
                <h2 class="text-xl mb-4 opacity-50">{{ user.fullname }}</h2>
                <h3 class="texl-xl font-bold mb-4">
                    {{ user.username }}'s Books
                </h3>
                <div id="book-list" class="flex w-full h-32 gap-5 overflow-x-auto items-center align-middle justify-center">
                    <!-- <img src="https://hololive.hololivepro.com/wp-content/uploads/2022/04/%E3%82%A2%E3%83%A1%E3%83%AA%E3%82%A2.png" class="h-full w-auto object-contain shadow-xl""/>
                    <img src="https://hololive.hololivepro.com/wp-content/uploads/2023/01/Takanashi-Kiara_thumb.png" class="h-full w-auto object-contain shadow-xl""/>
                    <img src="https://hololive.hololivepro.com/wp-content/uploads/2022/04/%E3%81%84%E3%81%AA%E3%81%AB%E3%81%99.png" class="h-full w-auto object-contain shadow-xl""/>
                    <img src="https://hololive.hololivepro.com/wp-content/uploads/2022/04/%E3%81%90%E3%82%89.png" class="h-full w-auto object-contain shadow-xl""/>
                    <img src="https://hololive.hololivepro.com/wp-content/uploads/2022/04/%E3%82%A2%E3%83%A1%E3%83%AA%E3%82%A2.png" class="h-full w-auto object-contain shadow-xl""/>
                    <img src="https://hololive.hololivepro.com/wp-content/uploads/2023/10/IRyS_list_thumb.png" class="h-full w-auto object-contain shadow-xl""/>
                    <img src="https://hololive.hololivepro.com/wp-content/uploads/2023/07/Nerissa-Ravencroft_list_thumb.png" class="h-full w-auto object-contain shadow-xl""/>
                    <img src="https://hololive.hololivepro.com/wp-content/uploads/2023/02/FriendA_thumb.png" class="h-full w-auto object-contain shadow-xl""/> -->
                </div>
            </div>
            <div class="w-full md:mb-0 mb-16">
                <h3 class="texl-xl font-bold mb-4">
                    Recent Reviews
                </h3>
                <div id="review-list" class="h-[75vh] w-full overflow-y-auto flex flex-col gap-3">
                    <!-- <div class="border-2 rounded-xl p-2 shadow-lg flex gap-6 max-h-32">
                        <img src="https://images.goodsmile.info/cgm/images/product/20230703/14604/117609/large/9672319311faf53ec723ee366bc4346c.jpg" class="h-full aspect-square object-cover shadow-xl rounded-xl"/>
                        <div>
                            <h4 class="font-extrabold">Spy x Family Season 2</h4>
                            <i class="fa-solid fa-star"> 4.5</i>
                            <br class="mb-4"/>
                            SUISEI NO GOTOKU ARAWARETA SUTAA NO GENSEKI! AIDORU VTUBER NO HOSHIMACHI SEUISEI DESU! SUI-CHAN WA--? KYOU MO KAWAII!
                        </div>
                    </div>
                    <div class="border-2 rounded-xl p-2 shadow-lg flex gap-6 max-h-32">
                        <img src="https://m.media-amazon.com/images/I/51PCNNihXeL._AC_UF894,1000_QL80_.jpg" class="h-full aspect-square object-cover shadow-xl rounded-xl"/>
                        <div>
                            <h4 class="font-extrabold">Spy x Family Season 2</h4>
                            <i class="fa-solid fa-star"> 4.5</i>
                            <br class="mb-4"/>
                            SUISEI NO GOTOKU ARAWARETA SUTAA NO GENSEKI! AIDORU VTUBER NO HOSHIMACHI SEUISEI DESU! SUI-CHAN WA--? KYOU MO KAWAII!
                        </div>
                    </div>
                    <div class="border-2 rounded-xl p-2 shadow-lg flex gap-6 max-h-32">
                        <img src="https://cdn.kyou.id/items/197241-nendoroid-shishiro-botan-hololive-production.jpg.webp" class="h-full aspect-square object-cover shadow-xl rounded-xl"/>
                        <div>
                            <h4 class="font-extrabold">Spy x Family Season 2</h4>
                            <i class="fa-solid fa-star"> 4.5</i>
                            <br class="mb-4"/>
                            SUISEI NO GOTOKU ARAWARETA SUTAA NO GENSEKI! AIDORU VTUBER NO HOSHIMACHI SEUISEI DESU! SUI-CHAN WA--? KYOU MO KAWAII!
                        </div>
                    </div>
                    <div class="border-2 rounded-xl p-2 shadow-lg flex gap-6 max-h-32">
                        <img src="https://cdn.kyou.id/items/244714-nendoroid-amane-kanata-hololive-production.jpg.webp" class="h-full aspect-square object-cover shadow-xl rounded-xl"/>
                        <div>
                            <h4 class="font-extrabold">Spy x Family Season 2</h4>
                            <i class="fa-solid fa-star"> 4.5</i>
                            <br class="mb-4"/>
                            SUISEI NO GOTOKU ARAWARETA SUTAA NO GENSEKI! AIDORU VTUBER NO HOSHIMACHI SEUISEI DESU! SUI-CHAN WA--? KYOU MO KAWAII!
                        </div>
                    </div>
                    <div class="border-2 rounded-xl p-2 shadow-lg flex gap-6 max-h-32">
                        <img src="https://cdn.kyou.id/items/184581-nendoroid-enrico-pucci-jojos-bizzare-adventure.jpg.webp" class="h-full aspect-square object-cover shadow-xl rounded-xl"/>
                        <div>
                            <h4 class="font-extrabold">Spy x Family Season 2</h4>
                            <i class="fa-solid fa-star"> 4.5</i>
                            <br class="mb-4"/>
                            SUISEI NO GOTOKU ARAWARETA SUTAA NO GENSEKI! AIDORU VTUBER NO HOSHIMACHI SEUISEI DESU! SUI-CHAN WA--? KYOU MO KAWAII!
                        </div>
                    </div>
                    <div class="border-2 rounded-xl p-2 shadow-lg flex gap-6 max-h-32">
                        <img src="https://cdn.kyou.id/items/121739-nendoroid-dio-brando-jojos-bizzare-adventure-stardust-crusader-re-release.jpg.webp" class="h-full aspect-square object-cover shadow-xl rounded-xl"/>
                        <div>
                            <h4 class="font-extrabold">Spy x Family Season 2</h4>
                            <i class="fa-solid fa-star"> 4.5</i>
                            <br class="mb-4"/>
                            SUISEI NO GOTOKU ARAWARETA SUTAA NO GENSEKI! AIDORU VTUBER NO HOSHIMACHI SEUISEI DESU! SUI-CHAN WA--? KYOU MO KAWAII!
                        </div>
                    </div>
                    <div class="border-2 rounded-xl p-2 shadow-lg flex gap-6 max-h-32">
                        <img src="https://cdn.kyou.id/items/241881-nendoroid-hayase-yuuka-blue-archive.jpg.webp" class="h-full aspect-square object-cover shadow-xl rounded-xl"/>
                        <div>
                            <h4 class="font-extrabold">Spy x Family Season 2</h4>
                            <i class="fa-solid fa-star"> 4.5</i>
                            <br class="mb-4"/>
                            SUISEI NO GOTOKU ARAWARETA SUTAA NO GENSEKI! AIDORU VTUBER NO HOSHIMACHI SEUISEI DESU! SUI-CHAN WA--? KYOU MO KAWAII!
                        </div>
                    </div> -->
                </div>
            </div>
        </section>
    <script src="{% static 'js/profile.js' %}"></script>
    <script type="module" src="{% static 'js/firebase-upload.js' %}"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"/>
{% endblock content %}